### ISSUE TITLE
执行package后崩溃

### ISSUE THREAD

**Issue by zhongwuq** [aliyun/surftrace#4]
Traceback (most recent call last):
  File "/usr/local/bin/surfGuide", line 11, in <module>
    load_entry_point('surfGuide==0.4', 'console_scripts', 'surfGuide')()
  File "/usr/local/lib/python3.6/site-packages/surfGuide/surfGuide.py", line 84, in main
    guide.loop()
  File "/usr/local/lib/python3.6/site-packages/surfGuide/conBase.py", line 283, in loop
    CconBase._loop.run()
  File "/usr/local/lib64/python3.6/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib64/python3.6/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib64/python3.6/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/lib64/python3.6/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib64/python3.6/site-packages/urwid/raw_display.py", line 417, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib64/python3.6/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib64/python3.6/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/lib64/python3.6/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib64/python3.6/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib64/python3.6/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/local/lib64/python3.6/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib64/python3.6/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/usr/local/lib64/python3.6/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/local/lib64/python3.6/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/local/lib64/python3.6/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/local/lib/python3.6/site-packages/surfGuide/editExpression.py", line 62, in _cb_pack_clk
    w = CpackProduct(self, self._lines, self._fName)
  File "/usr/local/lib/python3.6/site-packages/surfGuide/packProduct.py", line 38, in __init__
    super(CpackProduct, self).__init__()
  File "/usr/local/lib/python3.6/site-packages/surfGuide/conBase.py", line 82, in __init__
    self.view = self.setupView()
  File "/usr/local/lib/python3.6/site-packages/surfGuide/packProduct.py", line 131, in setupView
    self._archs[0].set_state(True)
  File "/usr/local/lib64/python3.6/site-packages/urwid/wimp.py", line 243, in set_state
    self._emit('change', state)
  File "/usr/local/lib64/python3.6/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/local/lib64/python3.6/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/local/lib64/python3.6/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/local/lib/python3.6/site-packages/surfGuide/packProduct.py", line 122, in _cb_check_change
    self._setupVers(w, stat)
  File "/usr/local/lib/python3.6/site-packages/surfGuide/packProduct.py", line 115, in _setupVers
    count += self.__setupVers(w, self._vers)
  File "/usr/local/lib/python3.6/site-packages/surfGuide/packProduct.py", line 105, in __setupVers
    verList = requests.get("%s%s.txt" % (verUrl, arch)).content.split("\n")[:-1]
TypeError: a bytes-like object is required, not 'str'

**Comment by liaozhaoyan** [comment]
python2 和3 兼容问题导致， 已经做了兼容处理，修复 0.4.1版本修复

**Comment by liaozhaoyan** [comment]
另外需要明确是否同时在pip2和pip3上同时已经安装了surfGuide的的问题，可能更新的是pip2新版本，但是执行的还是pip3旧版本。
